version: "3.7"

services:
  # web:
  #   container_name: vote-server-web
  #   build: .
  #   environment:
  #     DB_DATABASE: voting
  #     DB_HOST: db
  #     DB_TYPE: postgres
  #     DB_USER: main
  #     DB_PASSWORD: mysql_strong_password
  #   links:
  #     - db
  #   ports:
  #     - 8080:80
  db:
    container_name: vote-server-test-db
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_DB: voting
      POSTGRES_USER: main
      POSTGRES_PASSWORD: mysql_strong_password
    ports:
      - 5432:5432
